In [2]:
"""neural network for prediction with some input and one output"""

#function for mult two vectors
def mult_vec(a,b):
    assert len(a) == len(b)
    output = 0 
    for i in range(len(a)):
        output += a[i] * b[i]
    return output

#function for rearization neural network
def neural_net(input_s, weights):
    return mult_vec(input_s, weights)

print(neural_net([.1,.2,0], [5,3,1]));

1.1


In [3]:
import numpy as np

In [4]:
"""Code with use NumPy"""
weights = np.array([0.1, 0.2, 0]) # weights for our neural network
input_s = np.array([5,3,1])

def neural_net(input_s, weights):
    return input_s.dot(weights)

print(neural_net(input_s, weights))

1.1


In [5]:
"""Neural network with hidden layer for calculate prediction with NumPy"""
ih_wgt = np.array([[.1, .2, -.1],
                  [-.1, .1, .9],
                  [.1, .4, .1]]).T
hp_wgt = np.array([
    [.3, 1.1, -.3],
    [.1, .2, .0],
    [.0, 1.3, .1]
]).T
weights = [ih_wgt, hp_wgt]

def neural_net(input_s, weigts):
    hid = input_s.dot(weights[0]) #first layer(hidden)
    return hid.dot(weights[1]) # second layer(out)

input_s = np.array([8.5, .65, 1.2])

print(neural_net(input_s, weights))


[0.2135 0.145  0.5065]


In [6]:
"""Secrets of NumPy"""
a = np.array([1,2,3,4]) #This is vector
b = np.array([5,6,7,8]) # This is too vector, but vector others numbers
c = np.array([
    [.1, .2, .3],
    [.5, -.4, .3],
    [-.1, -.2, -.15]
]) # But this is Matrix(Vector of vectors)
d = np.zeros((3,4))
e = np.random.rand(2,5)

In [7]:
"""Function for calculate error"""
MSE = lambda y_pred, y: (y_pred - y) ** 2

"""Gradient descent"""

weight = .1
alpha = .01

def neural_net(input_s, weight):
    return input_s * weight
#Dataset for prediction
goal_predict = 1
data = 8.5

pred = neural_net(data, weight)
error = MSE(pred, goal_predict)
print("Befor learning.\nError : {0}. Predict : {1}. Should be Predict : {2}".format(error, pred, goal_predict))

#Learning Gradient descent - w_new = w_prew - lr*func(w_prew)
weight -= alpha*2*data*(pred-goal_predict)
pred = neural_net(data, weight)
error = MSE(pred, goal_predict)

print("\nAfter one iteration learning\nError : {0}. Predict : {1}. Should be Predict : {2}".format(error, pred, goal_predict))


Befor learning.
Error : 0.022499999999999975. Predict : 0.8500000000000001. Should be Predict : 1

After one iteration learning
Error : 0.004455562500000012. Predict : 1.06675. Should be Predict : 1


In [8]:
MSE = lambda y_pred, y_goal: (y_pred - y_goal) ** 2

input_s = 1.3
goal_predict = 1.0
weight = .1
lr = 0.01

def neural_net(input_s, weight):
    return input_s * weight

for i in range(170):
    print("iteration : ____________{0}_____________".format(i))
    predict = neural_net(input_s, weight)
    error = MSE(predict, goal_predict)
    loss = 2 * input_s * (predict - goal_predict)
    weight = weight - lr * loss
    print("Error : {0}.\nweight : {1}.\nPredict : {2}".format(error, weight, predict)  )

iteration : ____________0_____________
Error : 0.7569.
weight : 0.12262.
Predict : 0.13
iteration : ____________1_____________
Error : 0.706598272836.
weight : 0.144475444.
Predict : 0.15940600000000002
iteration : ____________2_____________
Error : 0.6596394757231052.
weight : 0.16559217399280002.
Predict : 0.18781807720000002
iteration : ____________3_____________
Error : 0.6158014456868682.
weight : 0.1859951585118434.
Predict : 0.21526982619064003
iteration : ____________4_____________
Error : 0.5748767841620465.
weight : 0.2057085221541431.
Predict : 0.2417937060653964
iteration : ____________5_____________
Error : 0.5366718757859903.
weight : 0.22475557410533306.
Predict : 0.267421078800386
iteration : ____________6_____________
Error : 0.5010059724006302.
weight : 0.2431588357005728.
Predict : 0.292182246336933
iteration : ____________7_____________
Error : 0.46771033792945693.
weight : 0.26094006705389344.
Predict : 0.3161064864107447
iteration : ____________8_____________
Erro

In [10]:
#Learning neural net with some inputs with gradient descent
MSE = lambda y_pred, y_goal: (y_pred - y_goal) ** 2

def ele_mul(number, vectors):
    return number * np.array(vectors)

def neural_net(input_s, weights):
    return np.array(input_s).dot(np.array(weights))
#init weights and dataset
weights = [0.1, 0.2, -.1]

toes = [8.5, 9.5, 9.9, 9.0, 9.1]
wlrec = [.65, .8, .8, 1., .3]
nfans = [1.2, 1.3, .5, 1., .3]

win_or_lose = [1, 1, 0, 1, 0]

#For very fast calculate outputs

input_s = list(map(list, zip(toes, wlrec, nfans)))
predicts = [neural_net(i, weights) for i in input_s]
error = [MSE(i[0], i[1]) for i in zip(predicts, win_or_lose)]

for iteration in range(15):
    for i in input_s:
        predict = neural_net(i, weights)
        error = MSE(predict, win_or_lose[input_s.index(i)])
        delta = (predict - win_or_lose[input_s.index(i)]) * np.array(i)
        weights = np.array(weights) - 0.01 * delta
        print("______Iteration : {0}_____\nError : {1}".format(iteration, error));



______Iteration : 0_____
Error : 0.01959999999999997
______Iteration : 0_____
Error : 0.00920870544400002
______Iteration : 0_____
Error : 1.272130955257488
______Iteration : 0_____
Error : 0.988002819757008
______Iteration : 0_____
Error : 0.5852657185327654
______Iteration : 1_____
Error : 0.800462745700978
______Iteration : 1_____
Error : 0.015029630408529983
______Iteration : 1_____
Error : 1.2068179445880673
______Iteration : 1_____
Error : 0.9699015627098198
______Iteration : 1_____
Error : 0.5661225975974965
______Iteration : 2_____
Error : 0.7767760031304282
______Iteration : 2_____
Error : 0.014141688505273354
______Iteration : 2_____
Error : 1.180476778119032
______Iteration : 2_____
Error : 0.9518836123786807
______Iteration : 2_____
Error : 0.5475984716687005
______Iteration : 3_____
Error : 0.753759619066155
______Iteration : 3_____
Error : 0.013292208452959479
______Iteration : 3_____
Error : 1.154789590685136
______Iteration : 3_____
Error : 0.9342815445749251
______Iter

In [22]:
import random

weights = np.array([.5, .48, -.7])
alpha = 0.1

street = np.array( [
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1],
    [0, 1, 1],
    [1, 0, 1] ] )

walk_and_stop = np.array( [0, 1, 0, 1, 1, 0] )

for i in range(200):
    #Init dataset for learning net
    tmp = random.randint(0,5)
    input_s = street[tmp]
    goal = walk_and_stop[tmp]
    
    #Learning
    
    predict = input_s.dot(weights)
    error = (predict - goal) ** 2
    weights -= (predict - goal)*input_s*alpha
    
    print("**********\nIteration : {0}.\nError : {1}\n. \nWeights : \n{2}\n\n".format(i, error, weights))
print("Test:\nInput : (1, 1, 1)\n Predict : {0}\n Goal predict : {1}".format(
np.array([1, 1, 1]).dot(weights), 1))

**********
Iteration : 0.
Error : 0.48999999999999994
. 
Weights : 
[ 0.5   0.48 -0.63]


**********
Iteration : 1.
Error : 0.42250000000000004
. 
Weights : 
[ 0.565  0.545 -0.565]


**********
Iteration : 2.
Error : 1.0404
. 
Weights : 
[ 0.565  0.647 -0.463]


**********
Iteration : 3.
Error : 0.6658560000000001
. 
Weights : 
[ 0.565   0.7286 -0.3814]


**********
Iteration : 4.
Error : 0.42614784000000006
. 
Weights : 
[ 0.565    0.79388 -0.31612]


**********
Iteration : 5.
Error : 0.27273461760000006
. 
Weights : 
[ 0.565     0.846104 -0.263896]


**********
Iteration : 6.
Error : 0.06964109881599997
. 
Weights : 
[ 0.565      0.846104  -0.2375064]


**********
Iteration : 7.
Error : 0.05640929004095998
. 
Weights : 
[ 0.565       0.846104   -0.21375576]


**********
Iteration : 8.
Error : 0.1351678166310976
. 
Weights : 
[ 0.565       0.88286918 -0.17699058]


**********
Iteration : 9.
Error : 0.08650740264390251
. 
Weights : 
[ 0.565       0.91228132 -0.14757844]


**********
It

In [2]:
import numpy as np
def relu(x):
    return (x > 0)*x

def relu2deriv(output):
    return output > 0
np.random.seed(1)

alpha = 0.2
hidden_size = 4

street = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1] ])
walk_and_stop = np.array([1, 1, 0, 0])

weights_0_1 = 2*np.random.random((3, hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size, 1)) - 1

#layer_0 = street[0]
#layer_1 = relu(np.dot(layer_0, weights_0_1)) for one iteration
#layer_2 = np.dot(layer_1, weights_1_2)

for iteration in range(60):
    layer_2_error = 0
    for i in range(len(street)):
        layer_0 = street[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        
        layer_2_error += np.sum((layer_2-walk_and_stop[i:i+1]) ** 2)
        
        layer_2_delta = (walk_and_stop[i:i+1]-layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
        
        if (iteration % 10 == 9):
            print("Error : {0}\n".format(layer_2_error))


Error : 0.02317222265722177

Error : 0.37697998088916795

Error : 0.5585446349508787

Error : 0.6342311598444467

Error : 6.583974603752558e-05

Error : 0.18340014797885185

Error : 0.31497070417381795

Error : 0.35838407676317513

Error : 1.2854807174765666e-14

Error : 0.032716692228431515

Error : 0.07944050755997109

Error : 0.0830183113303298

Error : 2.438025114683471e-24

Error : 0.0016192127634249867

Error : 0.006448232304230192

Error : 0.006467054957103705

Error : 0.0

Error : 6.299054636709449e-05

Error : 0.0003292669000750734

Error : 0.0003292669000750734

Error : 0.0

Error : 2.8586146897158e-06

Error : 1.5055622665134859e-05

Error : 1.5055622665134859e-05



In [1]:
#Dataset for recognition MNIST of third layer neural net
from keras.datasets import mnist
import sys, numpy as np
(x_train, y_train), (x_test, y_test) = mnist.load_data()



Using TensorFlow backend.


In [55]:
images, labels = (x_train[0:1000].reshape(1000,28*28)/255, y_train[0:1000])
one_hot_labels = np.zeros((len(y_test),10))
for i, l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i, l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)
relu = lambda x: (x >= 0)*x
relu_derive = lambda x: x > 0

alpha, iterations, hidden_size, pixels_per_image, num_labels = (0.005, 30, 100, 784, 10)
weights_0_l = 0.2*np.random.random((pixels_per_image,hidden_size)) - 0.1
weights_l_2 = 0.2*np.random.random((hidden_size,num_labels)) - 0.1


for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(len(images)):
        layer_0 = images[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_l))
        layer_2 = np.dot(layer_1, weights_l_2)
        error += np.sum((labels[i:i+1] - layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == np.argmax(labels[i:i+1]))
        layer_2_delta = (labels[i:i+1] - layer_2)
        layer_1_delta = (layer_2_delta.dot(weights_l_2.T) * relu_derive(layer_1))
        
        weights_l_2 += alpha * (layer_1.T).dot(layer_2_delta)
        weights_0_l += alpha * (layer_0.T).dot(layer_1_delta)
    print("\r"+ \
" I:"+str(j)+ \
" Error:" + str(error/float(len(images)))[0:5] +\
" Correct:" + str(correct_cnt/float(len(images))))



 I:0 Error:0.664 Correct:0.634
 I:1 Error:0.435 Correct:0.808
 I:2 Error:0.356 Correct:0.87
 I:3 Error:0.305 Correct:0.9
 I:4 Error:0.268 Correct:0.918
 I:5 Error:0.241 Correct:0.932
 I:6 Error:0.218 Correct:0.94
 I:7 Error:0.200 Correct:0.953
 I:8 Error:0.185 Correct:0.962
 I:9 Error:0.172 Correct:0.965
 I:10 Error:0.161 Correct:0.971
 I:11 Error:0.151 Correct:0.975
 I:12 Error:0.142 Correct:0.979
 I:13 Error:0.134 Correct:0.985
 I:14 Error:0.127 Correct:0.989
 I:15 Error:0.121 Correct:0.992
 I:16 Error:0.115 Correct:0.993
 I:17 Error:0.110 Correct:0.993
 I:18 Error:0.105 Correct:0.996
 I:19 Error:0.100 Correct:0.996
 I:20 Error:0.096 Correct:0.997
 I:21 Error:0.092 Correct:0.998
 I:22 Error:0.088 Correct:0.998
 I:23 Error:0.085 Correct:1.0
 I:24 Error:0.081 Correct:1.0
 I:25 Error:0.078 Correct:1.0
 I:26 Error:0.075 Correct:1.0
 I:27 Error:0.072 Correct:1.0
 I:28 Error:0.070 Correct:1.0
 I:29 Error:0.067 Correct:1.0


In [56]:
if (j % 10 == 0 or j == iterations - 1):
    error, correct_cnt = (0.0, 0)
    
    for i in range(len(test_images)):
        layer_0 = test_images[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_l))
        layer_2 = np.dot(layer_1, weights_l_2)
        
        error += np.sum((test_labels[i]-layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))
        
print(" Test-Err:" + str(error/float(len(test_images)))[0:5] +\
" Test-Acc:" + str(correct_cnt/float(len(test_images))))

 Test-Err:0.293 Test-Acc:0.8877


In [73]:
#dropout in neural network

images, labels = (x_train[0:1000].reshape(1000,28*28)/255, y_train[0:1000])
one_hot_labels = np.zeros((len(y_test),10))
for i, l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i, l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)
relu = lambda x: (x >= 0)*x
relu_derive = lambda x: x > 0

alpha, iterations, hidden_size, pixels_per_image, num_labels = (0.005, 100, 100, 784, 10)
weights_0_l = 0.2*np.random.random((pixels_per_image,hidden_size)) - 0.1
weights_l_2 = 0.2*np.random.random((hidden_size,num_labels)) - 0.1


for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(len(images)):
        layer_0 = images[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_l))
        #drop init
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        layer_1 *= dropout_mask * 2        
        layer_2 = np.dot(layer_1, weights_l_2)
        
        error += np.sum((labels[i:i+1] - layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == np.argmax(labels[i:i+1]))
        
        layer_2_delta = (labels[i:i+1] - layer_2)
        layer_1_delta = (layer_2_delta.dot(weights_l_2.T) * relu_derive(layer_1))
        layer_1_delta *= dropout_mask
        
        weights_l_2 += alpha * (layer_1.T).dot(layer_2_delta)
        weights_0_l += alpha * (layer_0.T).dot(layer_1_delta)
    #print("\r"+" I:"+str(j)+" Error:" + str(error/float(len(images)))[0:5] " Correct:" + str(correct_cnt/float(len(images))))
print("OK")

OK


In [74]:
if (j % 10 == 0 or j == iterations - 1):
    error, correct_cnt = (0.0, 0)
    
    for i in range(len(test_images)):
        layer_0 = test_images[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_l))
        layer_2 = np.dot(layer_1, weights_l_2)
        
        error += np.sum((test_labels[i]-layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))
        
print(" Test-Err:" + str(error/float(len(test_images)))[0:5] +\
" Test-Acc:" + str(correct_cnt/float(len(test_images))))

 Test-Err:0.283 Test-Acc:0.8804


In [76]:
#Batches for Neural net. Пакетный градиентный спуск
images, labels = (x_train[0:1000].reshape(1000,28*28)/255, y_train[0:1000])
one_hot_labels = np.zeros((len(y_test),10))
for i, l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i, l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)
relu = lambda x: (x >= 0)*x
relu_derive = lambda x: x > 0

alpha, iterations, hidden_size, pixels_per_image, num_labels = (0.001, 300, 100, 784, 10)
weights_0_l = 0.2*np.random.random((pixels_per_image,hidden_size)) - 0.1
weights_l_2 = 0.2*np.random.random((hidden_size,num_labels)) - 0.1
batch_size = 100

for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(int(len(images)/batch_size)):
        batch_start, batch_end = ((i * batch_size), ((i+1)*batch_size))
        layer_0 = images[batch_start:batch_end]
        layer_1 = relu(np.dot(layer_0, weights_0_l))
        #drop init
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        layer_1 *= dropout_mask * 2        
        layer_2 = np.dot(layer_1, weights_l_2)
        
        error += np.sum((labels[batch_start:batch_end] - layer_2) ** 2)
        for k in range(batch_size):
            correct_cnt += int(np.argmax(layer_2[k:k+1]) == np.argmax(labels[k+batch_start:batch_start+k+1]))
        
            layer_2_delta = (labels[batch_start:batch_end] - layer_2) / batch_size
            layer_1_delta = (layer_2_delta.dot(weights_l_2.T) * relu_derive(layer_1))
            layer_1_delta *= dropout_mask
        
            weights_l_2 += alpha * (layer_1.T).dot(layer_2_delta)
            weights_0_l += alpha * (layer_0.T).dot(layer_1_delta)
    if (j % 10 == 0 or j == iterations - 1):
        error, correct_cnt = (0.0, 0)

        for i in range(len(test_images)):
            layer_0 = test_images[i:i+1]
            layer_1 = relu(np.dot(layer_0, weights_0_l))
            layer_2 = np.dot(layer_1, weights_l_2)

            error += np.sum((test_labels[i]-layer_2) ** 2)
            correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))

        print(" Test-Err:" + str(error/float(len(test_images)))[0:5] +\
    " Test-Acc:" + str(correct_cnt/float(len(test_images))))


 Test-Err:0.824 Test-Acc:0.3752
 Test-Err:0.543 Test-Acc:0.7264
 Test-Err:0.464 Test-Acc:0.7757
 Test-Err:0.418 Test-Acc:0.8061
 Test-Err:0.389 Test-Acc:0.8197
 Test-Err:0.366 Test-Acc:0.8317
 Test-Err:0.351 Test-Acc:0.8445
 Test-Err:0.340 Test-Acc:0.8513
 Test-Err:0.331 Test-Acc:0.8534
 Test-Err:0.323 Test-Acc:0.8585
 Test-Err:0.316 Test-Acc:0.8625
 Test-Err:0.312 Test-Acc:0.8641
 Test-Err:0.306 Test-Acc:0.8642
 Test-Err:0.302 Test-Acc:0.8667
 Test-Err:0.301 Test-Acc:0.8703
 Test-Err:0.297 Test-Acc:0.8691
 Test-Err:0.296 Test-Acc:0.8726
 Test-Err:0.295 Test-Acc:0.8733
 Test-Err:0.292 Test-Acc:0.8733
 Test-Err:0.288 Test-Acc:0.8746
 Test-Err:0.290 Test-Acc:0.8748
 Test-Err:0.287 Test-Acc:0.8767
 Test-Err:0.287 Test-Acc:0.876
 Test-Err:0.287 Test-Acc:0.877
 Test-Err:0.286 Test-Acc:0.8761
 Test-Err:0.285 Test-Acc:0.8773
 Test-Err:0.285 Test-Acc:0.8757
 Test-Err:0.283 Test-Acc:0.8788
 Test-Err:0.281 Test-Acc:0.8778
 Test-Err:0.282 Test-Acc:0.8758
 Test-Err:0.282 Test-Acc:0.8776


In [ ]:
images, labels = (x_train[0:1000].reshape(1000,28*28)/255, y_train[0:1000])
one_hot_labels = np.zeros((len(y_test),10))
for i, l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i, l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)

#Function for activation neuron in hidden and output layers
def tanh(x):
    return np.tanh(x)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derive(x):
    return sigmoid(x)*(1-sigmoid(x))
    
def tanh_derive(x):
    return 1 - (np.tanh(x)) ** 2

def softmax(x):
    temp = np.exp(x)
    return temp/(np.sum(temp, axis=1, keepdims=True))


alpha, iterations, hidden_size, pixels_per_image, num_labels = (2, 500, 100, 784, 10)
batch_size = 100

#Weights (input, hidden), (hidden, output)
weights_0_l = 0.02*np.random.random((pixels_per_image,hidden_size)) - 0.01
weights_l_2 = 0.02*np.random.random((hidden_size,num_labels)) - 0.01


for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(int(len(images)/batch_size)):
        batch_start, batch_end = ((i * batch_size), ((i+1)*batch_size))
        layer_0 = images[batch_start:batch_end]
        layer_1 = tanh(np.dot(layer_0, weights_0_l))
        #drop init
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        layer_1 *= dropout_mask * 2        
        layer_2 = softmax(np.dot(layer_1, weights_l_2))
        
        error += np.sum((labels[batch_start:batch_end] - layer_2) ** 2)
        for k in range(batch_size):
            correct_cnt += int(np.argmax(layer_2[k:k+1]) == np.argmax(labels[k+batch_start:batch_start+k+1]))
        
            layer_2_delta = (labels[batch_start:batch_end] - layer_2) / (batch_size*layer_2.shape[0])
            
            layer_1_delta = (layer_2_delta.dot(weights_l_2.T) * tanh_derive(layer_1))
            layer_1_delta *= dropout_mask
        
            weights_l_2 += alpha * (layer_1.T).dot(layer_2_delta)
            weights_0_l += alpha * (layer_0.T).dot(layer_1_delta)
            
    if (j % 10 == 0 or j == iterations - 1):
        error, correct_cnt = (0.0, 0)

        for i in range(len(test_images)):
            layer_0 = test_images[i:i+1]
            layer_1 = tanh(np.dot(layer_0, weights_0_l))
            layer_2 = softmax(np.dot(layer_1, weights_l_2))

            error += np.sum((test_labels[i]-layer_2) ** 2)
            correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))

        print(" Test-Err: "+str(j // 10) + " - "+str(error/float(len(test_images)))[0:5] +\
    " Test-Acc:" + str(correct_cnt/float(len(test_images))))

 Test-Err: 0 - 1.803 Test-Acc:0.098
 Test-Err: 1 - 0.372 Test-Acc:0.7352
 Test-Err: 2 - 0.388 Test-Acc:0.7583
 Test-Err: 3 - 0.411 Test-Acc:0.7082
 Test-Err: 4 - 0.412 Test-Acc:0.7133
 Test-Err: 5 - 0.417 Test-Acc:0.6989
 Test-Err: 6 - 0.412 Test-Acc:0.695
 Test-Err: 7 - 0.409 Test-Acc:0.7048


In [ ]:
#CNN - Сверточные нейронные сети
images, labels = (x_train[0:1000].reshape(1000,28*28)/255, y_train[0:1000])
one_hot_labels = np.zeros((len(y_test),10))
for i, l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i, l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)

#Function for activation neuron in hidden and output layers
def tanh(x):
    return np.tanh(x)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derive(x):
    return sigmoid(x)*(1-sigmoid(x))
    
def tanh_derive(x):
    return 1 - (np.tanh(x)) ** 2

def softmax(x):
    temp = np.exp(x)
    return temp/(np.sum(temp, axis=1, keepdims=True))


alpha, iterations = 2, 300
pixels_per_image, num_labels = (784, 10)
batch_size = 128

input_rows = 28
input_cols = 28

kernel_rows = 3
kernel_cols = 3
num_kernels = 16

hidden_size = (input_rows - kernel_rows)*(input_cols - kernel_cols)*num_kernels

kernels = 0.02*np.random.random((kernel_rows*kernel_cols, num_kernels)) - 0.01
weights_l_2 = 0.02*np.random.random((hidden_size,num_labels)) - 0.01

def get_image_section(layer, row_from, row_to, col_from, col_to):
    section = layer[:, row_from:row_to, col_from:col_to]
    return section.reshape(-1, 1, row_to-row_from, col_to-col_from)

for j in range(iterations):
    correct_cnt = 0
    for i in range(int(len(images)/batch_size)):
        batch_start, batch_end = i*batch_size, (i+1)*batch_size
        layer_0 = images[batch_start:batch_end]
        layer_0 = layer_0.reshape(layer_0.shape[0],28,28)
        layer_0.shape
        
        sects = []
        for row_start in range(layer_0.shape[1]-kernel_rows):
            for col_start in range(layer_0.shape[2]-kernel_cols):
                sect = get_image_section(layer_0,
                                        row_start,
                                        row_start+kernel_rows,
                                        col_start,
                                        col_start+kernel_cols)
                sects.append(sect)
        expanded_input = np.concatenate(sects, axis=1)
        es = expanded_input.shape
        
        flattened_input = expanded_input.reshape(es[0]*es[1], -1)
        kernel_output = flattened_input.dot(kernels)
        
        layer_1 = tanh(kernel_output.reshape(es[0], -1))
        
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        
        layer_1 *= dropout_mask*2
        layer_2 = softmax(np.dot(layer_1, weights_l_2))
        
        for k in range(batch_size):
            label_set = labels[batch_start+k:batch_start+k+1]
            _inc = int(np.argmax(layer_2[k:k+1]==np.argmax(label_set)))
            correct_cnt += _inc
            layer_2_delta = (labels[batch_start:batch_end]-layer_2) / (batch_size*layer_2.shape[0])
            layer_1_delta = layer_2_delta.dot(weights_l_2.T) * tanh_derive(layer_1)
            layer_1_delta *= dropout_mask
            
            weights_l_2 += alpha * (layer_1.T).dot(layer_2_delta)
            l1d_reshape = layer_1_delta.reshape(kernel_output.shape)
            k_update= flattened_input.T.dot(l1d_reshape)
            kernels -= alpha*k_update
            
    test_correct_cnt = 0          
    for i in range(len(test_images)):
        layer_0 = test_images
        layer_0 = layer_0.reshape(layer_0.shape[0],28,28)
        layer_0.shape
        sects = []
        for row_start in range(layer_0.shape[1]-kernel_rows):
            for col_start in range(layer_0.shape[2]-kernel_cols):
                sect = get_image_section(layer_0,row_start,row_start+kernel_rows, col_start, col_start+kernel_cols)
                sects.append(sect)
            expanded_input = np.concatenate(sects, axis=1)
            es = expanded_input.shape

            flattened_input = expanded_input.reshape(es[0]*es[1], -1)
            kernel_output = flattened_input.dot(kernels)

            layer_1 = tanh(kernel_output.reshape(es[0], -1))

            dropout_mask = np.random.randint(2, size=layer_1.shape)

            layer_1 *= dropout_mask*2
            layer_2 = softmax(np.dot(layer_1.T, weights_l_2))

            test_correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))
            if(j % 1 == 0):
                print("\n"+"I:" + str(j) +" Test-Acc:"+str(test_correct_cnt/float(len(test_images)))+ "Train-Acc:" + str(correct_cnt/float(len(images))))
        
            
        


/home/dcoder/anaconda3/envs/ml/lib/python3.5/site-packages/ipykernel_launcher.py:30: RuntimeWarning: invalid value encountered in true_divide



I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0

I:0 Test-Acc:0.0Train-Acc:0.0


In [3]:
import sys
f = open('reviews.txt')
raw_rewiews = f.readlines()
f.close()

f = open('labels.txt')
raw_labels = f.readlines()
f.close()

tokens = list(map(lambda x: set(x.split()),raw_rewiews))

vocab = set()
for sent in tokens:
    for word in sent:
        if len(word) > 0:
            vocab.add(word)
vocab = list(vocab)

word2index = {}
for i, word in enumerate(vocab):
    word2index[word] = i
    
input_dataset = []
for sent in tokens:
    sent_indeces = []
    for word in sent:
        try:
            sent_indeces.append(word2index[word])
        except:
            ""
    input_dataset.append(list(set(sent_indeces)))
target_dataset = []
for label in raw_labels:
    if label == 'positive\n':
        target_dataset.append(1)
    else:
        target_dataset.append(0)
print("Dataset download OK")
    
    
    

Dataset download OK


In [13]:
import numpy as np
np.random.seed(1)

def sigmoid(x):
    return 1/(1 + np.exp(-x))

alpha, iterations = 0.1, 2
hidden_size = 100

weights_0_1 = 0.2 * np.random.random((len(vocab), hidden_size)) -0.1
weights_1_2 = 0.2 * np.random.random((hidden_size, 1)) - 0.1

correct, total = 0,0 
for iter in range(iterations):
    for i in range(len(input_dataset)-1000):
        x, y = (input_dataset[i], target_dataset[i])
        layer_1 = sigmoid(np.sum(weights_0_1[x],axis=0))
        layer_2 = sigmoid(np.dot(layer_1, weights_1_2))
        
        layer_2_delta = layer_2 - y
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)
        
        weights_0_1[x] -= layer_1_delta *alpha
        weights_1_2 -= np.outer(layer_1, layer_2_delta) * alpha
                  
                  
correctjtotal = (0,0)
                  
for i in range(len(input_dataset)-1000,len(input_dataset)) :
    x = input_dataset[i]
    у = target_dataset[i]
    layer_1 = sigmoid(np.sum(weights_0_1[x],axis=0))
    layer_2 = sigmoid(np.dot(layer_1,weights_1_2))
    if(np.abs(layer_2 - y) < 0.5):
        correct += 1
    total += 1
print("Test Accuracy:" + str(correct / float(total)))
    

Test Accuracy:0.552


In [2]:
def delete_white_space(string):
    begin, end = 0,0
    check_b, check_e = False, False
    for i in range(len(string)):
        if string[i] not in [' ', '\n', '\r'] and not check_b:
            begin = i
            check_b = True
        if string[len(string)-1-i] not in [' ', '\n', '\r'] and not check_e:
            end = len(string)-1-i
            check_e = True
        if check_e and check_b:
            break
    return string[begin:end+1]
delete_white_space("    Hello    \nworld \n\n")

'Hello    \nworld'